/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Basketball;

import java.sql.*;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author Ayush
 */
public class AddStats extends javax.swing.JFrame {

    /**
     * Creates new form AddStats
     */
    public AddStats() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2-getWidth()/2,size.height/2-getHeight()/2);
        team();
        this.setTitle("  BASKETBALL PLAYER MANAGER");
        ImageIcon img = new ImageIcon("images/logomini.png");
        this.setIconImage(img.getImage());
    }

     Connection con1;
     
    PreparedStatement insert;
    PreparedStatement pst1;
    PreparedStatement pst;
    ResultSet rs;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        txtturnover = new javax.swing.JTextField();
        txtblocks = new javax.swing.JTextField();
        txtplayers = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtfga = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtfgm = new javax.swing.JTextField();
        txtassists = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtrebounds = new javax.swing.JTextField();
        txtgp = new javax.swing.JTextField();
        txtteam = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 153, 0));
        jLabel8.setText("BLOCKS");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 480, -1, -1));

        txtturnover.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        txtturnover.setForeground(new java.awt.Color(51, 153, 0));
        txtturnover.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtturnover, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 320, 110, 33));

        txtblocks.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        txtblocks.setForeground(new java.awt.Color(51, 153, 0));
        txtblocks.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtblocks, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 470, 110, 32));

        txtplayers.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        txtplayers.setForeground(new java.awt.Color(51, 153, 0));
        txtplayers.setMaximumRowCount(100);
        getContentPane().add(txtplayers, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 130, 249, 40));

        jLabel6.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 153, 0));
        jLabel6.setText("SELECT PLAYER");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, -1, -1));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 153, 0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Basketball/add5.png"))); // NOI18N
        jButton3.setText("ADD");
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 153, 0), 5, true));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 560, 180, 70));

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(51, 153, 0));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Basketball/exit9.png"))); // NOI18N
        jButton4.setText("EXIT");
        jButton4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 153, 0), 5, true));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 560, 180, 70));

        jLabel2.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 153, 0));
        jLabel2.setText("FIELD GOALS ATTEMPTED");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 260, -1, -1));

        jLabel3.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 153, 0));
        jLabel3.setText("FIELD GOALS MADE");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 340, 190, -1));

        txtfga.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        txtfga.setForeground(new java.awt.Color(51, 153, 0));
        txtfga.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtfga, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 250, 110, 34));

        jLabel9.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 153, 0));
        jLabel9.setText("ASSISTS");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 420, -1, -1));

        txtfgm.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        txtfgm.setForeground(new java.awt.Color(51, 153, 0));
        txtfgm.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtfgm, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 330, 110, 33));

        txtassists.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        txtassists.setForeground(new java.awt.Color(51, 153, 0));
        txtassists.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtassists, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 410, 110, 34));

        jLabel4.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 153, 0));
        jLabel4.setText("GAMES PLAYED");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 260, -1, -1));

        jLabel7.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 153, 0));
        jLabel7.setText("REBOUNDS");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 410, -1, -1));

        jLabel5.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 153, 0));
        jLabel5.setText("TURNOVERS");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 330, -1, -1));

        txtrebounds.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        txtrebounds.setForeground(new java.awt.Color(51, 153, 0));
        txtrebounds.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtrebounds, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 400, 110, 34));

        txtgp.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        txtgp.setForeground(new java.awt.Color(51, 153, 0));
        txtgp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtgp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgpActionPerformed(evt);
            }
        });
        getContentPane().add(txtgp, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 250, 110, 34));

        txtteam.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        txtteam.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                txtteamItemStateChanged(evt);
            }
        });
        txtteam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtteamActionPerformed(evt);
            }
        });
        getContentPane().add(txtteam, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 130, 250, 40));

        jLabel10.setFont(new java.awt.Font("Eras Bold ITC", 1, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 153, 0));
        jLabel10.setText("STATISTICS");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Basketball/kyrie5.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents
   public void team(){
    try{
     Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/basketball player manager?serverTimezone=UTC","root","");
            Statement stmt=con.createStatement();
            String query = "SELECT * from team ";
            ResultSet rs = stmt.executeQuery(query);
            
            while(rs.next()){
                txtteam.addItem(rs.getString("teamname"));
            }
    }
    catch(Exception e){
    
    }
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
            // TODO add your handling code here:
            String name = txtplayers.getSelectedItem().toString();
            String fga = txtfga.getText();
            String fgm = txtfgm.getText();
            String games_played = txtgp.getText();
            String turnover = txtturnover.getText();
            
            String assists = txtassists.getText();
            String rebound = txtrebounds.getText();
            String block = txtblocks.getText();

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
             con1 = DriverManager.getConnection("jdbc:mysql://localhost/basketball player manager?serverTimezone=UTC","root","");
            pst = con1.prepareStatement("INSERT into stats(playername,fga,fgm,games_played,turnover,assist,rebound,block)values(?,?,?,?,?,?,?,?)");
            
            pst.setString(1, name);
            pst.setString(2, fga);
            pst.setString(3, fgm);
            pst.setString(4, games_played);
            pst.setString(5, turnover);
            pst.setString(6, assists);
            pst.setString(7, rebound);
            pst.setString(8, block);
           
            

            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Stats Registered");
            txtplayers.setSelectedIndex(0);
            txtfga.setText("");
            txtfgm.setText("");
            txtgp.setText("");
            txtturnover.setText("");
            
            txtassists.setText("");
            txtrebounds.setText("");
            txtblocks.setText("");
            txtfgm.requestFocus();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddStats.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddStats.class.getName()).log(Level.SEVERE, null, ex);
        }
           
            

       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
       dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtgpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgpActionPerformed

    private void txtteamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtteamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtteamActionPerformed

    private void txtteamItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_txtteamItemStateChanged
        // TODO add your handling code here:
           try{
     Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/basketball player manager?serverTimezone=UTC","root","");
            Statement stmt = con.createStatement();
            String query = "SELECT * FROM player WHERE team = '"+txtteam.getSelectedItem()+"'";
            ResultSet rs = stmt.executeQuery(query);
            txtplayers.removeAllItems();
           
            while(rs.next()){
                
                txtplayers.addItem(rs.getString("name"));
             }
            }
    catch(Exception e){
    
    
    }                                        

    }//GEN-LAST:event_txtteamItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddStats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddStats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddStats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddStats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddStats().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtassists;
    private javax.swing.JTextField txtblocks;
    private javax.swing.JTextField txtfga;
    private javax.swing.JTextField txtfgm;
    private javax.swing.JTextField txtgp;
    private javax.swing.JComboBox<String> txtplayers;
    private javax.swing.JTextField txtrebounds;
    private javax.swing.JComboBox<String> txtteam;
    private javax.swing.JTextField txtturnover;
    // End of variables declaration//GEN-END:variables
}
