/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Basketball;

import java.sql.*;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author Ayush
 */
public class PlayerRegistration extends javax.swing.JFrame {

    /**
     * Creates new form PlayerRegistration
     */
    public PlayerRegistration() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2-getWidth()/2,size.height/2-getHeight()/2);
        team();
        this.setTitle("  BASKETBALL PLAYER MANAGER");
        ImageIcon img = new ImageIcon("images/logomini.png");
        this.setIconImage(img.getImage());
    }
Connection con;
    PreparedStatement pst;
    PreparedStatement pst1;
    ResultSet rs;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtname = new javax.swing.JTextField();
        txtheight = new javax.swing.JTextField();
        txtteam = new javax.swing.JComboBox<>();
        txtnumber = new javax.swing.JTextField();
        txtweight = new javax.swing.JTextField();
        txtcountry = new javax.swing.JTextField();
        txtsalary = new javax.swing.JTextField();
        txtdob = new javax.swing.JTextField();
        txtpos = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Eras Bold ITC", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(230, 31, 38));
        jLabel3.setText("NAME");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Eras Bold ITC", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(230, 31, 38));
        jLabel4.setText("TEAM");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Eras Bold ITC", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(230, 31, 38));
        jLabel5.setText("POSITION");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, -1, -1));

        jLabel6.setFont(new java.awt.Font("Eras Bold ITC", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(230, 31, 38));
        jLabel6.setText("HEIGHT");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, -1, -1));

        jLabel7.setFont(new java.awt.Font("Eras Bold ITC", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(230, 31, 38));
        jLabel7.setText("WEIGHT");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 360, -1, -1));

        jLabel8.setFont(new java.awt.Font("Eras Bold ITC", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(230, 31, 38));
        jLabel8.setText("JERSEY NUMBER");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 430, -1, -1));

        jLabel9.setFont(new java.awt.Font("Eras Bold ITC", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(230, 31, 38));
        jLabel9.setText("D.O.B");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 500, -1, -1));

        jLabel10.setFont(new java.awt.Font("Eras Bold ITC", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(230, 31, 38));
        jLabel10.setText("COUNTRY");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 570, -1, -1));

        jLabel11.setFont(new java.awt.Font("Eras Bold ITC", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(230, 31, 38));
        jLabel11.setText("SALARY");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 640, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Eras Bold ITC", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(230, 31, 38));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Basketball/save.png"))); // NOI18N
        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 540, 170, 60));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Eras Bold ITC", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(230, 31, 38));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Basketball/exit11.png"))); // NOI18N
        jButton2.setText("EXIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 610, 170, 60));

        txtname.setBackground(new java.awt.Color(255, 255, 255));
        txtname.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        txtname.setForeground(new java.awt.Color(230, 31, 38));
        txtname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtname.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(230, 31, 38), 4, true));
        txtname.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        getContentPane().add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 90, 270, 40));

        txtheight.setBackground(new java.awt.Color(255, 255, 255));
        txtheight.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        txtheight.setForeground(new java.awt.Color(230, 31, 38));
        txtheight.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtheight.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(230, 31, 38), 4, true));
        txtheight.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(txtheight, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 290, 270, 40));

        txtteam.setBackground(new java.awt.Color(255, 255, 255));
        txtteam.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        txtteam.setForeground(new java.awt.Color(230, 31, 38));
        txtteam.setBorder(null);
        txtteam.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(txtteam, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 160, 270, 40));

        txtnumber.setBackground(new java.awt.Color(255, 255, 255));
        txtnumber.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        txtnumber.setForeground(new java.awt.Color(230, 31, 38));
        txtnumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtnumber.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(230, 31, 38), 4, true));
        txtnumber.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(txtnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 420, 270, 40));

        txtweight.setBackground(new java.awt.Color(255, 255, 255));
        txtweight.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        txtweight.setForeground(new java.awt.Color(230, 31, 38));
        txtweight.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtweight.setToolTipText(" IN POUNDS (ex - 200 lbs)");
        txtweight.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(230, 31, 38), 4, true));
        txtweight.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(txtweight, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 350, 270, 40));

        txtcountry.setBackground(new java.awt.Color(255, 255, 255));
        txtcountry.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        txtcountry.setForeground(new java.awt.Color(230, 31, 38));
        txtcountry.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtcountry.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(230, 31, 38), 4, true));
        txtcountry.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(txtcountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 560, 270, 40));

        txtsalary.setBackground(new java.awt.Color(255, 255, 255));
        txtsalary.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        txtsalary.setForeground(new java.awt.Color(230, 31, 38));
        txtsalary.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtsalary.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(230, 31, 38), 4, true));
        txtsalary.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(txtsalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 630, 270, 40));

        txtdob.setBackground(new java.awt.Color(255, 255, 255));
        txtdob.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        txtdob.setForeground(new java.awt.Color(230, 31, 38));
        txtdob.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtdob.setToolTipText("YYYY-MM-DD");
        txtdob.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(230, 31, 38), 4, true));
        txtdob.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(txtdob, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 490, 270, 40));

        txtpos.setBackground(new java.awt.Color(255, 255, 255));
        txtpos.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        txtpos.setForeground(new java.awt.Color(230, 31, 38));
        txtpos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Point Guard", "Shooting Guard", "Small Forward", "Power Forward", "Center" }));
        txtpos.setBorder(null);
        txtpos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(txtpos, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 230, 270, 40));

        jLabel1.setFont(new java.awt.Font("Eras Bold ITC", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(230, 31, 38));
        jLabel1.setText("PLAYER REGISTRATION");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, -1, -1));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(230, 194, 80));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Basketball/demar.jpg"))); // NOI18N
        jLabel13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1240, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents
 public void team()  {
    
          try {
              
              
              Class.forName("com.mysql.cj.jdbc.Driver");
               con = DriverManager.getConnection("jdbc:mysql://localhost/basketball player manager?serverTimezone=UTC","root","");
                 pst1 = con.prepareStatement("SELECT * FROM team");
                 rs = pst1.executeQuery();
                txtteam.removeAllItems();
                 
                 while(rs.next()){
                     txtteam.addItem(rs.getString("teamname"));
                 }
               
          } catch (ClassNotFoundException ex) {
              Logger.getLogger(PlayerRegistration.class.getName()).log(Level.SEVERE, null, ex);
          } catch (SQLException ex) {
              Logger.getLogger(PlayerRegistration.class.getName()).log(Level.SEVERE, null, ex);
          }
        
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:

            String name = txtname.getText();
             String team = txtteam.getSelectedItem().toString();
             String position = txtpos.getSelectedItem().toString();
             String height = txtheight.getText();
             String weight = txtweight.getText();
             String number = txtnumber.getText();
             String dob = txtdob.getText();
             String country = txtcountry.getText();
             String salary = txtsalary.getText();
            Class.forName("com.mysql.cj.jdbc.Driver");
               con = DriverManager.getConnection("jdbc:mysql://localhost/basketball player manager?serverTimezone=UTC","root","");
               pst = con.prepareStatement("INSERT into player(name,team,position,height,weight,number,dob,country,salary)values(?,?,?,?,?,?,?,?,?)");
               
            pst.setString(1, name);
            pst.setString(2, team);
            pst.setString(3, position);
            pst.setString(4, height);
            pst.setString(5, weight);
            pst.setString(6, number);
            pst.setString(7, dob);
            pst.setString(8, country);
            pst.setString(9, salary);
           
           
            
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Player Registered");
            txtname.setText("");
            txtpos.setSelectedIndex(0);
            txtheight.setText("");
            txtweight.setText("");
            txtdob.setText("");
            txtcountry.setText("");
            txtnumber.setText("");
            txtsalary.setText("");
            txtnumber.requestFocus();        
            txtteam.setSelectedIndex(0);
               
               
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PlayerRegistration.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
              Logger.getLogger(PlayerRegistration.class.getName()).log(Level.SEVERE, null, ex);
          }
         
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayerRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayerRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayerRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayerRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlayerRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtcountry;
    private javax.swing.JTextField txtdob;
    private javax.swing.JTextField txtheight;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtnumber;
    private javax.swing.JComboBox<String> txtpos;
    private javax.swing.JTextField txtsalary;
    private javax.swing.JComboBox<String> txtteam;
    private javax.swing.JTextField txtweight;
    // End of variables declaration//GEN-END:variables
}
