/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Basketball;


import java.awt.*;
import java.sql.*;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Ayush
 */
public class TeamRoster extends javax.swing.JFrame {

    /**
     * Creates new form TeamRoster
     */
    public TeamRoster() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2-getWidth()/2,size.height/2-getHeight()/2);
        team();
        this.setTitle("  BASKETBALL PLAYER MANAGER");
        ImageIcon img = new ImageIcon("images/logomini.png");
        this.setIconImage(img.getImage());
        this.setIconImage(img.getImage());
        table.getTableHeader().setFont(new Font("Eras Bold ITC",Font.BOLD,18));
        table.getTableHeader().setForeground(new Color(204,0,51));
        table.getTableHeader().setBackground(new Color(0,0,0));
        
    }
Connection con;
    PreparedStatement pst;
    PreparedStatement pst1;
    ResultSet rs;
    
    public void team()  {
    
          try {
              
              
              Class.forName("com.mysql.cj.jdbc.Driver");
               con = DriverManager.getConnection("jdbc:mysql://localhost/basketball player manager?serverTimezone=UTC","root","");
                 pst1 = con.prepareStatement("SELECT * FROM team");
                 rs = pst1.executeQuery();
                txtselect.removeAllItems();
                 
                 while(rs.next()){
                     txtselect.addItem(rs.getString("teamname"));
                 }
               
          } catch (ClassNotFoundException ex) {
              Logger.getLogger(TeamRoster.class.getName()).log(Level.SEVERE, null, ex);
          } catch (SQLException ex) {
              Logger.getLogger(TeamRoster.class.getName()).log(Level.SEVERE, null, ex);
          }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        txtselect = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Eras Bold ITC", 1, 70)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 51));
        jLabel2.setText("TEAM ROSTER");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Eras Bold ITC", 1, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3.setText("SELECT TEAM NAME");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 310, 40));

        jButton1.setBackground(new java.awt.Color(204, 0, 51));
        jButton1.setFont(new java.awt.Font("Eras Bold ITC", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Basketball/player.png"))); // NOI18N
        jButton1.setText("SHOW PLAYERS");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 120, 180, 50));

        jButton2.setBackground(new java.awt.Color(204, 0, 51));
        jButton2.setFont(new java.awt.Font("Eras Bold ITC", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Basketball/exit3.png"))); // NOI18N
        jButton2.setText("EXIT");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 120, 110, 50));

        jScrollPane1.setBorder(null);

        table.setBackground(new java.awt.Color(255, 255, 255));
        table.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        table.setForeground(new java.awt.Color(204, 0, 51));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NAME", "TEAM", "POSITION", "HEIGHT", "WEIGHT", "NUMBER", "DOB", "COUNTRY", "SALARY"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setGridColor(new java.awt.Color(255, 0, 51));
        table.setRowHeight(30);
        table.setSelectionForeground(new java.awt.Color(204, 0, 51));
        table.setShowVerticalLines(false);
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 1180, 410));

        txtselect.setBackground(new java.awt.Color(255, 255, 255));
        txtselect.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        txtselect.setForeground(new java.awt.Color(204, 0, 51));
        txtselect.setMaximumRowCount(100);
        txtselect.setAutoscrolls(true);
        txtselect.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 51), 4));
        txtselect.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(txtselect, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 250, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Basketball/heat.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-310, 0, 1790, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          try {
              int c;
              String team = txtselect.getSelectedItem().toString();
              // TODO add your handling code here:
              Class.forName("com.mysql.cj.jdbc.Driver");
              con = DriverManager.getConnection("jdbc:mysql://localhost/basketball player manager?serverTimezone=UTC","root","");
                      pst = con.prepareStatement("SELECT * FROM player WHERE team =  ?" );
                      pst.setString(1, team);   
                      ResultSet rs = pst.executeQuery();
                ResultSetMetaData Rss = rs.getMetaData();
            
                c= Rss.getColumnCount();
                
                DefaultTableModel Df = (DefaultTableModel)table.getModel();
                Df.setRowCount(0);
         
         while(rs.next())
         {
         Vector v2 = new Vector();
         
            for(int a = 1; a<=c; a++)
            {
                v2.add(rs.getString("id"));
                v2.add(rs.getString("name"));
                v2.add(rs.getString("team"));
                v2.add(rs.getString("position"));
                v2.add(rs.getString("height"));
                v2.add(rs.getString("weight"));
                v2.add(rs.getString("number"));
                v2.add(rs.getString("dob"));
                v2.add(rs.getString("country"));
                v2.add(rs.getString("salary"));
            }
            Df.addRow(v2);
         }
             txtselect.setSelectedIndex(0);
      
          } catch (ClassNotFoundException ex) {
              Logger.getLogger(TeamRoster.class.getName()).log(Level.SEVERE, null, ex);
          } catch (SQLException ex) {
              Logger.getLogger(TeamRoster.class.getName()).log(Level.SEVERE, null, ex);
          }
            
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeamRoster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeamRoster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeamRoster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeamRoster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeamRoster().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    private javax.swing.JComboBox<String> txtselect;
    // End of variables declaration//GEN-END:variables
}
