/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Basketball;

import java.awt.*;

import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.chart.*;
import org.jfree.chart.plot.*;
import java.lang.*;
/**
 *
 * @author Ayush
 */
public class UpdateStats extends javax.swing.JFrame {

    /**
     * Creates new form UpdateStats
     */
    public UpdateStats() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2-getWidth()/2,size.height/2-getHeight()/2);
          team();
        tableUpdate();
        this.setTitle("  BASKETBALL PLAYER MANAGER");
        ImageIcon img = new ImageIcon("images/logomini.png");
        this.setIconImage(img.getImage());
        jTable1.getTableHeader().setFont(new Font("Eras Bold ITC",Font.BOLD,12));
        jTable1.getTableHeader().setForeground(new Color(196, 36, 24));
       
        
    }
Connection con1;
    PreparedStatement insert;
    PreparedStatement pst1;
    PreparedStatement pst;
    ResultSet rs;
    
     public void team(){
    try{
     Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/basketball player manager?serverTimezone=UTC","root","");
            Statement stmt=con.createStatement();
            String query = "SELECT * from team  ";
            ResultSet rs = stmt.executeQuery(query);
            
            while(rs.next()){
                txtteam.addItem(rs.getString("teamname"));
            }
    }
    catch(Exception e){
    
    }
    }
 public void tableUpdate(){
      int c;
         try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/basketball player manager?serverTimezone=UTC","root","");
            insert = con1.prepareStatement("SELECT * FROM stats");
            
             ResultSet rs = insert.executeQuery();
                ResultSetMetaData Rss = rs.getMetaData();
            
                c= Rss.getColumnCount();
                
                DefaultTableModel Df = (DefaultTableModel)jTable1.getModel();
            
         Df.setRowCount(0);
         
         while(rs.next())
         {
         Vector v2 = new Vector();
         
            for(int a = 1; a<=c; a++)
            {
                 v2.add(rs.getString("stat_id"));
                v2.add(rs.getString("playername"));
                v2.add(rs.getString("fga"));
                v2.add(rs.getString("fgm"));
                v2.add(rs.getString("games_played"));
                v2.add(rs.getString("turnover"));
                v2.add(rs.getString("assist"));
                v2.add(rs.getString("rebound"));
                v2.add(rs.getString("block"));
                
                
            }
            Df.addRow(v2);
         }
            
           
            
        } catch (ClassNotFoundException ex) {
          
        }
           catch (SQLException ex) {
            
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtturnover = new javax.swing.JTextField();
        txtgp = new javax.swing.JTextField();
        txtfgm = new javax.swing.JTextField();
        txtfga = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtrebound = new javax.swing.JTextField();
        txtassist = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtblock = new javax.swing.JTextField();
        txtteam = new javax.swing.JComboBox<>();
        txtplayers = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Eras Bold ITC", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(196, 36, 24));
        jLabel2.setText("UPDATE STATISTICS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, -1, -1));

        jScrollPane1.setBorder(null);

        jTable1.setBackground(new java.awt.Color(0, 0, 0));
        jTable1.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STAT ID  ", "PLAYER NAME  ", "FIELD GOAL A  ", "FIELD GOAL M  ", "GAMES PLAYED  ", "TURNOVER  ", "ASSIST  ", "REBOUND  ", "BLOCK  "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(30);
        jTable1.setShowVerticalLines(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, 1040, 300));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Eras Bold ITC", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(196, 36, 24));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Basketball/best.png"))); // NOI18N
        jButton1.setText("SELECT PLAYER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 80, 210, 70));

        jLabel3.setFont(new java.awt.Font("Eras Bold ITC", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(196, 36, 24));
        jLabel3.setText("TEAM");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 50, -1));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Eras Bold ITC", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(196, 36, 24));
        jButton2.setText("DELETE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 320, 130, 60));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Eras Bold ITC", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(196, 36, 24));
        jButton3.setText("EXIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 320, 130, 60));

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Eras Bold ITC", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(196, 36, 24));
        jButton4.setText("UPDATE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 320, 130, 60));

        jLabel4.setFont(new java.awt.Font("Eras Bold ITC", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(196, 36, 24));
        jLabel4.setText("TURNOVER");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 250, -1, -1));

        jLabel5.setFont(new java.awt.Font("Eras Bold ITC", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(196, 36, 24));
        jLabel5.setText("GAMES PLAYED");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 190, -1, -1));

        txtturnover.setFont(new java.awt.Font("Eras Bold ITC", 1, 14)); // NOI18N
        txtturnover.setForeground(new java.awt.Color(196, 36, 24));
        txtturnover.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtturnover, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 240, 130, 40));

        txtgp.setFont(new java.awt.Font("Eras Bold ITC", 1, 14)); // NOI18N
        txtgp.setForeground(new java.awt.Color(196, 36, 24));
        txtgp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtgp, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 180, 130, 40));

        txtfgm.setFont(new java.awt.Font("Eras Bold ITC", 1, 14)); // NOI18N
        txtfgm.setForeground(new java.awt.Color(196, 36, 24));
        txtfgm.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtfgm, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 240, 130, 40));

        txtfga.setFont(new java.awt.Font("Eras Bold ITC", 1, 14)); // NOI18N
        txtfga.setForeground(new java.awt.Color(196, 36, 24));
        txtfga.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtfga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfgaActionPerformed(evt);
            }
        });
        getContentPane().add(txtfga, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, 130, 40));

        jLabel6.setFont(new java.awt.Font("Eras Bold ITC", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(196, 36, 24));
        jLabel6.setText("FIELD GOAL ATTEMPTED");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, -1, -1));

        jLabel7.setFont(new java.awt.Font("Eras Bold ITC", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(196, 36, 24));
        jLabel7.setText("FIELD GOAL MADE");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, -1, -1));

        txtrebound.setFont(new java.awt.Font("Eras Bold ITC", 1, 14)); // NOI18N
        txtrebound.setForeground(new java.awt.Color(196, 36, 24));
        txtrebound.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtrebound, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 240, 120, 40));

        txtassist.setFont(new java.awt.Font("Eras Bold ITC", 1, 14)); // NOI18N
        txtassist.setForeground(new java.awt.Color(196, 36, 24));
        txtassist.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtassist, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 180, 120, 40));

        jLabel8.setFont(new java.awt.Font("Eras Bold ITC", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(196, 36, 24));
        jLabel8.setText("ASSIST");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 190, -1, -1));

        jLabel9.setFont(new java.awt.Font("Eras Bold ITC", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(196, 36, 24));
        jLabel9.setText("REBOUND");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 250, -1, -1));

        jLabel10.setFont(new java.awt.Font("Eras Bold ITC", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(196, 36, 24));
        jLabel10.setText("BLOCKS");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, -1, -1));

        txtblock.setFont(new java.awt.Font("Eras Bold ITC", 1, 14)); // NOI18N
        txtblock.setForeground(new java.awt.Color(196, 36, 24));
        txtblock.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtblock, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 300, 130, 40));

        txtteam.setFont(new java.awt.Font("Eras Bold ITC", 1, 14)); // NOI18N
        txtteam.setForeground(new java.awt.Color(196, 36, 24));
        txtteam.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                txtteamItemStateChanged(evt);
            }
        });
        getContentPane().add(txtteam, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 190, 40));

        txtplayers.setFont(new java.awt.Font("Eras Bold ITC", 1, 14)); // NOI18N
        txtplayers.setForeground(new java.awt.Color(196, 36, 24));
        getContentPane().add(txtplayers, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, 190, 40));

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("Eras Bold ITC", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(196, 36, 24));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Basketball/chart.png"))); // NOI18N
        jButton5.setText("SHOW CHART");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 80, 210, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Basketball/demar4.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, 0, 1390, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtfgaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfgaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfgaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dispose();
              
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         
      try {  
             String name = txtplayers.getSelectedItem().toString();
             String fga = txtfga.getText();
             String fgm = txtfgm.getText();
             String games_played = txtgp.getText();
             String turnover = txtturnover.getText();
             String assist = txtassist.getText();
             String rebound = txtrebound.getText();
             String block = txtblock.getText();
             
             
          
            Class.forName("com.mysql.cj.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/basketball player manager?serverTimezone=UTC","root","");
            insert = con1.prepareStatement("update stats set fga = ?, fgm=? ,games_played=? ,turnover=? ,assist=? ,rebound=? ,block=?  where playername =?");
            
            
            insert.setString(1, fga);
            insert.setString(2, fgm);
            insert.setString(3, games_played);
            insert.setString(4, turnover);
            insert.setString(5, assist);
            insert.setString(6, rebound);
            insert.setString(7, block);
            insert.setString(8, name);
            
            insert.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Player Updated");
            txtfga.setText("");
            txtplayers.setSelectedIndex(0);
            txtfgm.setText("");
            txtgp.setText("");
            txtturnover.setText("");
            txtassist.setText("");
            txtrebound.setText("");
            txtblock.setText("");
               
            tableUpdate();
               
            
        } catch (ClassNotFoundException ex) {
            
        }
         catch (SQLException ex) {
            
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
           DefaultTableModel Df = (DefaultTableModel)jTable1.getModel();
        int selectedIndex = jTable1.getSelectedRow();
        
        txtplayers.setSelectedItem(Df.getValueAt(selectedIndex, 1).toString());
        txtfga.setText(Df.getValueAt(selectedIndex, 2).toString());
        txtfgm.setText(Df.getValueAt(selectedIndex, 3).toString());
        txtgp.setText(Df.getValueAt(selectedIndex, 4).toString());
        txtturnover.setText(Df.getValueAt(selectedIndex, 5).toString());
         txtassist.setText(Df.getValueAt(selectedIndex, 6).toString());
        txtrebound.setText(Df.getValueAt(selectedIndex, 7).toString());
        txtblock.setText(Df.getValueAt(selectedIndex, 8).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
           try {
              int c;
              String team = txtplayers.getSelectedItem().toString();
              // TODO add your handling code here:
              Class.forName("com.mysql.cj.jdbc.Driver");
              con1 = DriverManager.getConnection("jdbc:mysql://localhost/basketball player manager?serverTimezone=UTC","root","");
                      pst = con1.prepareStatement("SELECT * FROM stats WHERE playername =  ?");
                      pst.setString(1, team);   
                      ResultSet rs = pst.executeQuery();
                ResultSetMetaData Rss = rs.getMetaData();
            
                c= Rss.getColumnCount();
                
                DefaultTableModel Df = (DefaultTableModel)jTable1.getModel();
                Df.setRowCount(0);
         
         while(rs.next())
         {
         Vector v2 = new Vector();
         
            for(int a = 1; a<=c; a++)
            {
                v2.add(rs.getString("stat_id"));
                v2.add(rs.getString("playername"));
                v2.add(rs.getString("fga"));
                v2.add(rs.getString("fgm"));
                v2.add(rs.getString("games_played"));
                v2.add(rs.getString("turnover"));
                v2.add(rs.getString("assist"));
                v2.add(rs.getString("rebound"));
                v2.add(rs.getString("block"));
                
            }
            Df.addRow(v2);
         }
             txtplayers.setSelectedIndex(0);
      
          } catch (ClassNotFoundException ex) {
              
          } catch (SQLException ex) {
              
          }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtteamItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_txtteamItemStateChanged
        // TODO add your handling code here:
        try{
     Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/basketball player manager?serverTimezone=UTC","root","");
            Statement stmt=con.createStatement();
            String query = "SELECT * FROM player WHERE team = '"+txtteam.getSelectedItem()+"'";
            ResultSet rs = stmt.executeQuery(query);
            txtplayers.removeAllItems();
           
            
            while(rs.next()){
                txtplayers.addItem(rs.getString("name"));
            }
    }
    catch(Exception e){
    
    }
    }//GEN-LAST:event_txtteamItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
           DefaultTableModel Df = (DefaultTableModel)jTable1.getModel();
        int selectedIndex = jTable1.getSelectedRow();
        
        try {
             
             int id = Integer.parseInt(Df.getValueAt(selectedIndex, 0).toString() );
            
                int dialogResult = JOptionPane.showConfirmDialog(null, "Do you want to remove the Player?","WARNING",JOptionPane.YES_NO_CANCEL_OPTION);
                        
                        if(dialogResult == JOptionPane.YES_OPTION)
                        {
                         Class.forName("com.mysql.cj.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/basketball player manager?serverTimezone=UTC","root","");
            insert = con1.prepareStatement("DELETE from stats where stat_id =?");
           
     
             insert.setInt(1, id);
             insert.executeUpdate();
         
            JOptionPane.showMessageDialog(this,"Record Deleted");
           
            
            txtfga.setText("");
            txtplayers.setSelectedIndex(0);
            txtfgm.setText("");
            txtgp.setText("");
            txtturnover.setText("");
            txtassist.setText("");
            txtrebound.setText("");
            txtblock.setText("");
               
            tableUpdate();
               
            
                       
             }
                
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Team.class.getName()).log(Level.SEVERE, null, ex);
        }
           catch (SQLException ex) {
            Logger.getLogger(Team.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String fga = txtfga.getText();
        String fgm = txtfgm.getText();
        
        DefaultPieDataset pieDataset = new DefaultPieDataset();
        pieDataset.setValue("Field Goal Attempted", new Integer(fga));
       
        pieDataset.setValue("Field Goal Made", new Integer(fgm));
        
        JFreeChart chart = ChartFactory.createPieChart3D("Field Goals Chart", pieDataset, true,true,true);
        PiePlot3D P = (PiePlot3D)chart.getPlot();
        
        ChartFrame frame = new ChartFrame("BASKETBALL PLAYER MANAGER",chart);
        frame.setBackground( Color.BLACK );
        frame.setVisible(true);
        frame.setSize(450,500);
        ImageIcon img = new ImageIcon("images/logomini.png");
        frame.setIconImage(img.getImage());
          Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        frame.setLocation(size.width/2-getWidth()/2,size.height/2-getHeight()/2);
        
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateStats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateStats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateStats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateStats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateStats().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtassist;
    private javax.swing.JTextField txtblock;
    private javax.swing.JTextField txtfga;
    private javax.swing.JTextField txtfgm;
    private javax.swing.JTextField txtgp;
    private javax.swing.JComboBox<String> txtplayers;
    private javax.swing.JTextField txtrebound;
    private javax.swing.JComboBox<String> txtteam;
    private javax.swing.JTextField txtturnover;
    // End of variables declaration//GEN-END:variables
}
