/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Basketball;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

import java.awt.*;

/**
 *
 * @author Ayush
 */
public class UpdatePlayer extends javax.swing.JFrame {

    /**
     * Creates new form UpdatePlayer
     */
     Connection con1;
    PreparedStatement insert;
    PreparedStatement pst1;
    ResultSet rs;
    
    public UpdatePlayer() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2-getWidth()/2,size.height/2-getHeight()/2);
        tableUpdate();
        team();
        this.setTitle("  BASKETBALL PLAYER MANAGER");
        ImageIcon img = new ImageIcon("images/logomini.png");
        this.setIconImage(img.getImage());
        jTable1.getTableHeader().setFont(new Font("Eras Bold ITC",Font.BOLD,18));
        jTable1.getTableHeader().setForeground(new Color(0, 0, 0));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtteam = new javax.swing.JComboBox<>();
        txtpos = new javax.swing.JComboBox<>();
        txtnumber = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtweight = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtheight = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtdob = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtcountry = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtsalary = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 51));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TEAM");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, -1, -1));

        jLabel3.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NAME");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, -1, -1));

        txtname.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        txtname.setForeground(new java.awt.Color(239, 83, 4));
        getContentPane().add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 260, 40));

        jLabel5.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("POSITION");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, -1, -1));

        txtteam.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        txtteam.setForeground(new java.awt.Color(239, 83, 4));
        getContentPane().add(txtteam, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 260, 40));

        txtpos.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        txtpos.setForeground(new java.awt.Color(239, 83, 4));
        txtpos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Point Guard", "Shooting Guard", "Small Forward", "Power Forward", "Center" }));
        getContentPane().add(txtpos, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 260, 40));

        txtnumber.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        txtnumber.setForeground(new java.awt.Color(239, 83, 4));
        getContentPane().add(txtnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 250, 240, 40));

        jLabel8.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("JERSEY NUMBER");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 260, -1, -1));

        txtweight.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        txtweight.setForeground(new java.awt.Color(239, 83, 4));
        txtweight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtweightActionPerformed(evt);
            }
        });
        getContentPane().add(txtweight, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 180, 240, 40));

        jLabel7.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("WEIGHT");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 190, -1, -1));

        txtheight.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        txtheight.setForeground(new java.awt.Color(239, 83, 4));
        getContentPane().add(txtheight, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 110, 240, 40));

        jLabel6.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("HEIGHT");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 120, -1, -1));

        jLabel9.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("D.O.B");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 190, -1, -1));

        txtdob.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        txtdob.setForeground(new java.awt.Color(239, 83, 4));
        getContentPane().add(txtdob, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 180, 230, 40));

        jLabel10.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("COUNTRY");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 260, -1, -1));

        txtcountry.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        txtcountry.setForeground(new java.awt.Color(239, 83, 4));
        getContentPane().add(txtcountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 250, 230, 40));

        jLabel11.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("SALARY");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 120, -1, -1));

        txtsalary.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        txtsalary.setForeground(new java.awt.Color(239, 83, 4));
        getContentPane().add(txtsalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 110, 230, 40));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(197, 195, 183));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Basketball/update3.png"))); // NOI18N
        jButton1.setText("UPDATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 630, 150, 60));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(197, 195, 183));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Basketball/exit7.png"))); // NOI18N
        jButton2.setText("EXIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 630, 150, 60));

        jScrollPane1.setBorder(null);

        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(239, 83, 4));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NAME", "TEAM", "POSITION", "HEIGHT", "WEIGHT", "NUMBER", "DOB", "COUNTRY", "SALARY"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(197, 195, 183));
        jTable1.setRowHeight(30);
        jTable1.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jTable1.setShowVerticalLines(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 1320, 280));

        jLabel1.setFont(new java.awt.Font("Eras Bold ITC", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("UPDATE PLAYER INFORMATION");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, -1, -1));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(197, 195, 183));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Basketball/delete3.png"))); // NOI18N
        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 630, 140, 60));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Basketball/kyrie3.jpeg"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, 0, 1660, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtweightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtweightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtweightActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel Df = (DefaultTableModel)jTable1.getModel();
        int selectedIndex = jTable1.getSelectedRow();
      try {  
             String name = txtname.getText();
             String team = txtteam.getSelectedItem().toString();
             String position = txtpos.getSelectedItem().toString();
             String height = txtheight.getText();
             String weight = txtweight.getText();
             String number = txtnumber.getText();
             String dob = txtdob.getText();
             String country = txtcountry.getText();
             String salary = txtsalary.getText();
             int id = Integer.parseInt(Df.getValueAt(selectedIndex, 0).toString() );
          
          
             
        
             
            Class.forName("com.mysql.cj.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/basketball player manager?serverTimezone=UTC","root","");
            insert = con1.prepareStatement("update player set name = ?, team=? ,position=? ,height=? ,weight=? ,number=? ,dob=? ,country=?,salary=? where id =?");
            insert.setString(1, name);
            insert.setString(2, team);
            insert.setString(3, position);
            insert.setString(4, height);
            insert.setString(5, weight);
            insert.setString(6, number);
            insert.setString(7, dob);
            insert.setString(8, country);
            insert.setString(9, salary);
            insert.setInt(10, id);
           
           
            
            insert.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Player Updated");
            txtname.setText("");
            txtpos.setSelectedIndex(0);
            txtheight.setText("");
            txtweight.setText("");
            txtdob.setText("");
            txtcountry.setText("");
            txtnumber.setText("");
            txtsalary.setText("");
            txtnumber.requestFocus();        
            txtteam.setSelectedIndex(0);
            tableUpdate();
               
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(UpdatePlayer.class.getName()).log(Level.SEVERE, null, ex);
        }
           catch (SQLException ex) {
            Logger.getLogger(UpdatePlayer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel Df = (DefaultTableModel)jTable1.getModel();
        int selectedIndex = jTable1.getSelectedRow();
        
        txtname.setText(Df.getValueAt(selectedIndex, 1).toString());
        txtteam.setSelectedItem(Df.getValueAt(selectedIndex, 2).toString());
        txtpos.setSelectedItem(Df.getValueAt(selectedIndex, 3).toString());
        txtheight.setText(Df.getValueAt(selectedIndex, 4).toString());
        txtweight.setText(Df.getValueAt(selectedIndex, 5).toString());
         txtnumber.setText(Df.getValueAt(selectedIndex, 6).toString());
        txtdob.setText(Df.getValueAt(selectedIndex, 7).toString());
        txtcountry.setText(Df.getValueAt(selectedIndex, 8).toString());
       
        txtsalary.setText(Df.getValueAt(selectedIndex, 9).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel Df = (DefaultTableModel)jTable1.getModel();
        int selectedIndex = jTable1.getSelectedRow();
        
        try {
             
             int id = Integer.parseInt(Df.getValueAt(selectedIndex, 0).toString() );
            
                int dialogResult = JOptionPane.showConfirmDialog(null, "Do you want to remove the Player?","WARNING",JOptionPane.YES_NO_CANCEL_OPTION);
                        
                        if(dialogResult == JOptionPane.YES_OPTION)
                        {
                         Class.forName("com.mysql.cj.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/basketball player manager?serverTimezone=UTC","root","");
            insert = con1.prepareStatement("DELETE from player where id =?");
           
     
             insert.setInt(1, id);
             insert.executeUpdate();
         
            JOptionPane.showMessageDialog(this,"Record Deleted");
           
            txtname.setText("");
            txtpos.setSelectedIndex(0);
            txtheight.setText("");
            txtweight.setText("");
            txtdob.setText("");
            txtcountry.setText("");
            txtnumber.setText("");
            txtsalary.setText("");
            txtnumber.requestFocus();        
            txtteam.setSelectedIndex(0);
            txtname.requestFocus();
            tableUpdate();
              
             }
                
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Team.class.getName()).log(Level.SEVERE, null, ex);
        }
           catch (SQLException ex) {
            Logger.getLogger(Team.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed
 public void team()  {
    
          try {
              
              
              Class.forName("com.mysql.cj.jdbc.Driver");
               con1 = DriverManager.getConnection("jdbc:mysql://localhost/basketball player manager?serverTimezone=UTC","root","");
                 pst1 = con1.prepareStatement("SELECT * FROM team");
                 rs = pst1.executeQuery();
                txtteam.removeAllItems();
                 
                 while(rs.next()){
                     txtteam.addItem(rs.getString("teamname"));
                 }
               
          } catch (ClassNotFoundException ex) {
              Logger.getLogger(UpdatePlayer.class.getName()).log(Level.SEVERE, null, ex);
          } catch (SQLException ex) {
              Logger.getLogger(UpdatePlayer.class.getName()).log(Level.SEVERE, null, ex);
          }
        
    }
    
    public void tableUpdate(){
      int c;
         try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/basketball player manager?serverTimezone=UTC","root","");
            insert = con1.prepareStatement("SELECT * FROM player");
            
             ResultSet rs = insert.executeQuery();
                ResultSetMetaData Rss = rs.getMetaData();
            
                c= Rss.getColumnCount();
                
                DefaultTableModel Df = (DefaultTableModel)jTable1.getModel();
            
         Df.setRowCount(0);
         
         while(rs.next())
         {
         Vector v2 = new Vector();
         
            for(int a = 1; a<=c; a++)
            {
                 v2.add(rs.getString("id"));
                v2.add(rs.getString("name"));
                v2.add(rs.getString("team"));
                v2.add(rs.getString("position"));
                v2.add(rs.getString("height"));
                v2.add(rs.getString("weight"));
                v2.add(rs.getString("number"));
                v2.add(rs.getString("dob"));
                v2.add(rs.getString("country"));
                v2.add(rs.getString("salary"));
            }
            Df.addRow(v2);
         }
            
            txtname.requestFocus();
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(UpdatePlayer.class.getName()).log(Level.SEVERE, null, ex);
        }
           catch (SQLException ex) {
            Logger.getLogger(UpdatePlayer.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
                               

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdatePlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdatePlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdatePlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdatePlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdatePlayer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtcountry;
    private javax.swing.JTextField txtdob;
    private javax.swing.JTextField txtheight;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtnumber;
    private javax.swing.JComboBox<String> txtpos;
    private javax.swing.JTextField txtsalary;
    private javax.swing.JComboBox<String> txtteam;
    private javax.swing.JTextField txtweight;
    // End of variables declaration//GEN-END:variables
}
